### ISSUE TITLE
Form report 2 - bottone salva nel editor avanzato e allegato non visualizzato 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront-ng2#12]
utente: ASOC1617_TEAM_167
link: http://testplatform.ascuoladiopencoesione.it/#/report/2/edit/45655 
browser: chrome

1. NON FUNZIONA IL BOTTONE SALVA NELLA PARTE DEL BODY DEL POST (allego foto di seguito)  HO PROVATO AD UTILIZZARLO MA CANCELLO TUTTO QUELLO CHE HAI FATO FIN A QUEL PUNTO. da verifica ulteriore risulta che cliccando su "salva" viene eseguito il LOGOUT

---- 

utente: ASOC1617_TEAM_167
link: http://www.ascuoladiopencoesione.it/testblogs/1/626/45655
browser: chrome
2. non ha salvato allegto:  mi carica il report ma sembra non aver preso il file che ho allegato.... 

@sirmmo

**Comment by sirmmo** [comment]
il bottone salva è stato eliminato
