### ISSUE TITLE
Report lezione 3 non visibile

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#13]
Dopo essermi loggato con l'utenza ASOC1617_TEAM_118 sul sito di test, e aver fatto click sul link che conduce al report della lezione 3 (http://testplatform.ascuoladiopencoesione.it/#/report/3/edit/46929), ottengo il titolo, ma nessun modulo da riempire.

**Comment by sirmmo** [comment]
risolto, era un disallineamento fra i due db.
