### ISSUE TITLE
Form Report 3.1 - Campo OEmbed

### ISSUE THREAD

**Issue by sirmmo** [AScuolaDiOpencoesione/ASOCFront-ng2#15]

**Comment by guglielmo** [comment]
Credo che questo sia bloccante per tutti i test del Report 3.1. Lo segno come prioritario.

**Comment by guglielmo** [comment]
Inserendo questo codice:
`<iframe width="900" height="800" frameborder="0" scrolling="no" src="//plot.ly/~mattybohan/428.embed"></iframe>`
nel campo `oembed`, il salvataggio procede correttamente, mentre all'invio si riceve questo messaggio:
"oembed: Il campo è obbligatorio"

**Comment by guglielmo** [comment]
Questo succede anche inserendo il link direttamente: http://plot.ly/~mattybohan/428.embed
