### ISSUE TITLE
Modulo 3.2: testi di aiuto dei campi

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#21]
**data**: "Inserire la data dell'evento in formato gg/mm/aaaa, es: 28/02/2017"
**luogo**: "Inserire un indirizzo e premere il pulsante Cerca, verificando che la geolocalizzazione sia corretta. es: via labicana, 27, roma"
**orario**: "Inserire l'orario dell'evento nel formato oo:mm, es: 11:45"
**locandina**: "Premere Choose File per selezionare un'immagine dal proprio PC, usare file di tipo Jpeg, Png, Gif, di dimensioni non superiori a [1Mb?]"

**Comment by sirmmo** [comment]
aggiunto testi di aiuto "cablati" al difuori della descrizione generale.
