### ISSUE TITLE
Modulo 3.2: coordinate della località non visualizzate, né salvate

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#25]
Inserisco una località, controllando che la georeferenziazione avvenga (la mappa è centrata sull'indirizzo inserito).
Salvo.
Visualizzo l'anteprima.

La sezione: Informazioni per raggiungere il luogo dell'evento
mostra questo codice, invece della mappa.
`{u'addr': u'via merulana, 19, roma'}`

Mi sposto sun un altro modulo, poi torno al 3.2.
L'indirizzo "via merulana, 19, roma" non compare nel campo della location.

Il comportamento corretto è che le coordinate restituite dal servizio di geolocalizzazione siano salvate, assieme all'indirizzo.
Il modulo deve anche visualizzare l'indirizzo salvato, nel campo "località", se questo è presente,
e la mappa deve essere centrata sulla location identificata dalle coordinate salavate nel DB.

Nella pagina del blog risultante (sia in anteprima che nel report finale, dopo l'invio), la mappa deve essere visualizzata, assieme all'indirizzo digitato dall'utente.

**Comment by sirmmo** [comment]
il dato ora viene correttamente visualizzato sulla anteprima ma non alla riapertura del report.
