### ISSUE TITLE
Form report 3.1 - problema invio 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront-ng2#27]
Report salvato e inviato ma risultano problemi con l'invio

account: 154

browser: firefox 

link: http://testplatform.ascuoladiopencoesione.it/#/report/3/edit/46376 

commento: Ok Salva, errore su Salva e invia che dice "C'è stato un problema nell'invio"

**Comment by sirmmo** [comment]
il motivo è che non era salvato l'embed... ho aggiunto il dato ed è a posto.
