### ISSUE TITLE
Form report 3.1 - visualizzazione oggetto embed

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront-ng2#30]
browser: firefox

utente: 10 

link: http://www.ascuoladiopencoesione.it/testblogs/3/111/46411?preview=true
http://www.ascuoladiopencoesione.it/testblogs/1/563/46411

Non si vede l'oggetto embed nell'anteprima dopo "salva", e anche nel blog dopo "salva ed invia"

**Comment by guglielmo** [comment]
Credo che qui il problema sia sul contenuto del campo oembed. Bisogna inserire un codice di embed, compreso del tag iframe, non solo la url.
In particolare per Youtube, nella pagina che indichi, il codice sarebbe:
<iframe width="560" height="315" src="https://www.youtube.com/embed/1fiacjVTorc" frameborder="0" allowfullscreen></iframe>

**Comment by sirmmo** [comment]
cambio lo "spiegone"?

**Comment by chiaracio** [comment]
si @guglielmo,  ma nella descrizione del campo dice di inserire il solo link (lo scorso anno era possibile) 
 @sirmmo puoi modificare con: 
"In questo campo serve a inserire un "oggetto embed". Se avete realizzato una visualizzazione interattiva con uno degli strumenti consigliati nella pillola 3.7, è necessario inserire di seguito il codice fornito dal servizio per incorporare la visualizzazione nel testo. Per esempio: "<iframe src="https://player.vimeo.com/video/201195751" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by guglielmo** [comment]
Sì, bisogna cambiare la spiegazione.
