### ISSUE TITLE
Report 3.2 - Immissione dati e visualizzazione

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront-ng2#33]
Utente 10

I flag su "tipologia di ospiti":

- nella visualizzazione post salvataggio http://www.ascuoladiopencoesione.it/testblogs/1/563/46412 ci sono 4 voci (Altro, Rappresentante istituzionale, Esperto open data (amici di ASOC), Esperto open data (ospite esterno), io avevo inserito soltanto "Rappresentante istituzionale" 

- le scelte sullo stesso campo non sono visibili  in back end dopo il salvataggio http://testplatform.ascuoladiopencoesione.it/#/report/4/edit/46412

**Comment by sirmmo** [comment]
dopo aver scoperto le profondità dell'inferno del confronto fra due stringhe in javascript e la profondità del dolore della gestione dello stato "checked" di una checkbox, è fatto. non è spuntato il checkbox, ma è grassetto il valore selezionato. Corretto anche il blog.
