### ISSUE TITLE
Monithon - Login Team Classe 1617

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront-ng2#44]
- dopo la registrazione cliccando su "il mio profilo" devono apparire solo i seguenti campi:
username
account twitter (facoltativo)
Città
Provicia
Regione

- aggiungere messaggio di "password errata" attualmente se sbaglio password non fa entrare ma non dice perchè

**Comment by chiaracio** [comment]
a registrazione avvenuta viene fuori questa schermata: 
<img width="500" alt="screen shot 2017-03-01 at 18 06 11" src="https://cloud.githubusercontent.com/assets/6087317/23471488/ccbc2c96-fea9-11e6-80ce-b24984d9be80.png">
e poi questa 
<img width="912" alt="screen shot 2017-03-01 at 18 06 58" src="https://cloud.githubusercontent.com/assets/6087317/23471499/e20d1eca-fea9-11e6-8eab-bf6168614241.png">
togliere tutto e inserire un bottone "compila il tuo report di monitoraggio"

**Comment by sirmmo** [comment]
Dopo il login rimando direttamente alla pagina dei report con in alto "Compila un Nuovo Report di Monitoraggio".
Volendo possono comunque modificare il loro profilo andando nel profilo utente in alto a dx.
