### ISSUE TITLE
Campi fonti obbligatori?

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#6]
Tutti i campi fonti, i tre alle _fonti istituzionali_ e i tre alle  _altre fonti_, sono obbligatori.
Dovrebbero essere opzionali, non è detto che tutti i report ne abbiano 3.

**Comment by sirmmo** [comment]
tolta l'obbligatorietà alla 2 e alla 3.
