### ISSUE TITLE
Form report 2 - Sintassi campi fonti non controllato

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#7]
I campi delle fonti, istituzionali e altre, non sono validati ed è possibile inserire qualsiasi stringa.
Visto che da quella stringa viene generato in automatico un link ipertestuale, 
si dovrebbe controllare che la stringa abbia un formato che segua il protocollo dei link ipertestuali:
`http[s]://domain.name.ext/path`

**Comment by sirmmo** [comment]
risolto utilizzando https://www.npmjs.com/package/ng2-validation

**Comment by guglielmo** [comment]
La validazione deve avvenire sia alla pressione del pulsante Salva che alla pressione del pulsante Invia.

**Comment by sirmmo** [comment]
la validazione ora avviene sempre.

**Comment by guglielmo** [comment]
Sono riuscito a inviare un modulo con dei link malformati.
http://www.ascuoladiopencoesione.it/testblogs/1/435/45648

**Comment by sirmmo** [comment]
ora faccio la validazione di requests.

`from requests.models import PreparedRequest
import requests.exceptions


def check_url(url):
    prepared_request = PreparedRequest()
    try:
        prepared_request.prepare_url(url, None)
        return True
    except requests.exceptions.MissingSchema, e:
        return False`
