### ISSUE TITLE
Tutti i report - Stile messaggi di errore

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#8]
L'utilizzo di finestre di popup dovrebbe essere evitato.

I messaggi di errore che seguono la compilazione errata di un form dovrebbero comparire come _flash messages_ in testa al modulo, e i campi dove l'errore avviene dovrebbero essere evidenziati (colore, outline, ...).

In questo modo l'utente capisce dove è avvenuto l'errore e può intervenire rapidamente.

**Comment by sirmmo** [comment]
viene gestito ora con un "growl" per le comunicazioni generali, poi con un dettaglio degli errori eventuali sulla singola riga del report.
