### ISSUE TITLE
Form Report  2 - Obbligatorietà dell'immagine

### ISSUE THREAD

**Issue by guglielmo** [AScuolaDiOpencoesione/ASOCFront-ng2#9]
L'immagine è segnalata come obbligatoria (l'asterisco), ma è possibile salvare il post e inviarlo senza aver caricato alcuna immagine.

Si veda : http://www.ascuoladiopencoesione.it/testblogs/1/621 come risultato finale dell'invio del report lezione 2 senza immagine.

Nel caso l'immagine non sia obbligatoria, eliminare l'asterisco che ne indica l'obbligatorietà.

**Comment by sirmmo** [comment]
fixed da commit precedente
